name: hark
options:
  bundleIdPrefix: com.craigsloggett
  deploymentTarget:
    macOS: '26.0'
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: '6.0'
    MARKETING_VERSION: 0.0.1
    CURRENT_PROJECT_VERSION: '1'
    GENERATE_INFOPLIST_FILE: false
targets:
  hark:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.craigsloggett.hark
        PRODUCT_NAME: hark
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: hark.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: true
        LD_RUNPATH_SEARCH_PATHS:
          - '@executable_path/../Frameworks'
