name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  version:
    name: Version
    runs-on: ubuntu-24.04

    outputs:
      new-release-published: ${{ steps.dry-run.outputs.new-release-published }}
      new-release-version: ${{ steps.dry-run.outputs.new-release-version }}

    steps:
      - name: Compute Version
        id: dry-run
        uses: craigsloggett/create-github-release@ca381e65d8d9bc17c1ce58c4bd8c54d8381d064b # v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

  build:
    name: Build
    needs: version
    if: needs.version.outputs.new-release-published == 'true'
    runs-on: macos-26
    env:
      HOMEBREW_REQUIRE_TAP_TRUST: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install XcodeGen
        shell: sh
        run: brew install xcodegen

      - name: Build
        shell: sh
        env:
          CONFIGURATION: Release
          VERSION: ${{ needs.version.outputs.new-release-version }}
        run: make build

      - name: Package App
        shell: sh
        env:
          CONFIGURATION: Release
        run: ditto -c -k --keepParent "build/Build/Products/${CONFIGURATION}/hark.app" hark.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: hark-app
          path: hark.zip

  release:
    name: GitHub
    needs:
      - version
      - build
    if: needs.version.outputs.new-release-published == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Create a GitHub Release
        id: release
        uses: craigsloggett/create-github-release@ca381e65d8d9bc17c1ce58c4bd8c54d8381d064b # v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: hark-app

      - name: Upload To Release
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          VERSION: ${{ steps.release.outputs.new-release-version }}
        run: gh release upload "v${VERSION}" hark.zip
