name: Test

on: pull_request

permissions:
  contents: read

concurrency:
  group: test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  HOMEBREW_REQUIRE_TAP_TRUST: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  xcode:
    name: Xcode
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install XcodeGen
        shell: sh
        run: brew install xcodegen

      - name: Test
        shell: sh
        run: make test
